'use strict';
const $=id=>document.getElementById(id),cl=(n,a,b)=>Math.max(a,Math.min(b,n)),eur=n=>Number(n||0).toLocaleString('de-DE',{style:'currency',currency:'EUR'}),num=id=>Math.max(0,Number($(id)?.value)||0);
const WATCH='dealfaz_watch_v2',RULES='dealfaz_rules_v2',FORECASTS='dealfaz_forecasts_v1',OUTCOMES='dealfaz_outcomes_v1';let c={};
function parseLocal(key,fallback){try{const x=JSON.parse(localStorage.getItem(key)||'null');return x??fallback}catch{return fallback}}
function getRules(){return{minProfit:20,minRoi:25,maxRisk:3,minQuality:50,...parseLocal(RULES,{})}}
function getWatch(){const x=parseLocal(WATCH,[]);return Array.isArray(x)?x:[]}
function setWatch(x){localStorage.setItem(WATCH,JSON.stringify(x.slice(0,50)));renderWatch()}
function getForecasts(){const x=parseLocal(FORECASTS,[]);return Array.isArray(x)?x:[]}
function setForecasts(x){localStorage.setItem(FORECASTS,JSON.stringify(x.slice(0,30)));renderForecasts()}
function getOutcomes(){const x=parseLocal(OUTCOMES,[]);return Array.isArray(x)?x:[]}
function setOutcomes(x){localStorage.setItem(OUTCOMES,JSON.stringify(x.slice(0,30)));renderOutcomes()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function calc(){let product=$('product').value.trim(),buy=num('buy'),sell=num('sell'),cost=num('cost'),sold=num('sold'),active=num('active'),comps=num('comps'),certainty=cl(num('certainty')||1,1,5),risk=cl(num('risk')||1,1,5),target=num('target'),days=Math.max(1,num('days')||30),sample=sold+active,sth=sample?sold/sample*100:0,profit=sell-buy-cost,roi=buy?profit/buy*100:0,margin=sell?profit/sell*100:0,roi30=roi*30/days;let quality=Math.round(cl(cl(sample/30*45,0,45)+cl(comps/8*30,0,30)+certainty/5*25,0,100));let score=cl(roi/50*35,0,35)+cl(sth/80*25,0,25)+(6-risk)/5*20+cl(margin/30*20,0,20),worst=sell*.85-buy-cost*1.15,best=sell*1.10-buy-cost*.95;if(profit<=0)score=Math.min(score,35);if(worst<0)score-=10;score=Math.round(cl(score,0,100));let verdict=score>=72&&profit>0&&worst>=0?'KAUFEN':score>=45&&profit>0?'VERHANDELN':'LIEGEN LASSEN';if(quality<45)verdict='DATEN PRÜFEN';let maxBuy=Math.max(0,(sell-cost)/(1+target/100));c={product,buy,sell,cost,sold,active,comps,certainty,risk,target,days,sth,quality,profit,roi,margin,roi30,worst,best,score,verdict,maxBuy,ts:Date.now()};$('score').textContent=score;$('verdict').textContent=verdict;$('sth').textContent=sth.toFixed(0)+' %';$('quality').textContent=quality+'/100';$('profit').textContent=eur(profit);$('roi').textContent=roi.toFixed(1)+' %';$('margin').textContent=margin.toFixed(1)+' %';$('roi30').textContent=roi30.toFixed(1)+' %';$('maxbuy').textContent=eur(maxBuy);$('worst').textContent=eur(worst);$('real').textContent=eur(profit);$('bestcase').textContent=eur(best);$('summary').textContent=product?product+' · '+(profit>=0?'rechnerischer Gewinn ':'rechnerischer Verlust ')+eur(Math.abs(profit)):'Trage Produkt und Werte ein.';$('gate').hidden=quality>=45;$('gate').textContent='Evidenz-Sperre: Datenbasis zu schwach für ein positives Kaufsignal.';let r=getRules(),ok=profit>=r.minProfit&&roi>=r.minRoi&&risk<=r.maxRisk&&quality>=r.minQuality;$('ruleStatus').innerHTML='Deine Kriterien: <strong class="'+(ok?'status-ok':'status-bad')+'">'+(ok?'ERFÜLLT':'NICHT ERFÜLLT')+'</strong>';counter();battle();markets(product)}
function counter(){let a=[];if(c.quality<45)a.push(['Datenbasis zu schwach','Datenqualität '+c.quality+'/100 – erst mehr vergleichbare Belege prüfen.']);if(c.worst<0)a.push(['Worst Case negativ','Im vorsichtigen Szenario '+eur(c.worst)+'.']);if(c.roi<c.target)a.push(['Ziel-ROI verfehlt','ROI '+c.roi.toFixed(1)+' % unter Ziel '+c.target.toFixed(0)+' %.']);if(c.risk>=4)a.push(['Risiko hoch','Von dir angegeben: '+c.risk+'/5.']);if(c.sth<30)a.push(['Sell-through niedrig','Aus deinen Eingaben '+c.sth.toFixed(0)+' %.']);if(c.buy>c.maxBuy)a.push(['Einkauf über Zielgrenze','Über Maximalpreis für den gewählten Ziel-ROI.']);if((c.sold+c.active)<10)a.push(['Kleine Stichprobe','Weniger als 10 beobachtete verkaufte + aktive Vergleiche.']);if(!a.length)a.push(['Keine starke Warnung aus deinen Eingaben','Zustand, Echtheit, Gebühren, Versand, Steuern und Plattformregeln trotzdem selbst prüfen.']);$('counterList').innerHTML=a.slice(0,3).map(x=>'<div class="counter"><b>'+x[0]+'</b><span>'+x[1]+'</span></div>').join('')}
function battle(){if(!c.buy)return;let bb=num('bBuy'),bs=num('bSell'),bc=num('bCost'),br=cl(num('bRisk')||1,1,5),bd=Math.max(1,num('bDays')||30),bp=bs-bb-bc,broi=bb?bp/bb*100:0,broi30=broi*30/bd;$('battleA').textContent=(c.product||'Deal A')+' · Gewinn '+eur(c.profit)+' · ROI '+c.roi.toFixed(1)+' % · ROI/30T '+c.roi30.toFixed(1)+' %';$('battleB').textContent=($('bName').value||'Deal B')+' · Gewinn '+eur(bp)+' · ROI '+broi.toFixed(1)+' % · ROI/30T '+broi30.toFixed(1)+' %';let w=$('battleWinner'),nameA=c.product||'Deal A',nameB=$('bName').value||'Deal B',diff=c.roi30-broi30;if(Math.abs(diff)>5){w.className='winner';w.textContent=(diff>0?nameA:nameB)+' liegt beim ROI pro 30 Tage vorn.'}else if(Math.abs(c.profit-bp)>10){w.className='winner';w.textContent=(c.profit>bp?nameA:nameB)+' liegt bei ähnlichem Kapitaltempo beim Gewinn vorn.'}else if(c.risk!==br){w.className='winner';w.textContent=(c.risk<br?nameA:nameB)+' hat bei ähnlichen Rechenwerten die niedrigere von dir angegebene Risikostufe.'}else{w.className='winner neutral';w.textContent='Nahe beieinander – echte Daten, Zustand und vollständige Kosten sollten entscheiden.'}}
function markets(q){let e=encodeURIComponent(q||''),amazon='https://iosghttnctdaociwltos.supabase.co/functions/v1/dealfaz-amazon#q='+e+'&source=dealfaz_home&campaign=market_sources&content=amazon',a=[['eBay verkauft','https://www.ebay.de/sch/i.html?_nkw='+e+'&LH_Sold=1&LH_Complete=1','nofollow noopener noreferrer'],['eBay aktiv','https://www.ebay.de/sch/i.html?_nkw='+e,'nofollow noopener noreferrer'],['Kleinanzeigen','https://www.kleinanzeigen.de/s-suchanfrage.html?keywords='+e,'nofollow noopener noreferrer'],['idealo','https://www.idealo.de/preisvergleich/MainSearchProductCategory.html?q='+e,'nofollow noopener noreferrer'],['Google Shopping','https://www.google.com/search?tbm=shop&q='+e,'nofollow noopener noreferrer'],['Amazon · Partnerlink',amazon,'nofollow sponsored noopener']];$('marketLinks').innerHTML=a.map(x=>'<a class="market" rel="'+x[2]+'" target="_blank" href="'+x[1]+'"><strong>'+x[0]+'</strong><span>Originalquelle öffnen →</span></a>').join('')}
function renderWatch(){let w=getWatch();$('watch').innerHTML=w.length?w.map((d,i)=>'<div class="watch"><div class="watchTop"><div><strong>'+esc(d.product||'Unbenannter Deal')+'</strong><br><small>'+eur(d.buy)+' → '+eur(d.sell)+' · '+(d.score??'–')+'/100 · '+esc(d.verdict||'')+'</small></div><div class="actions"><button class="secondary" onclick="loadWatch('+i+')">Laden</button><button class="secondary" onclick="removeWatch('+i+')">Entfernen</button></div></div></div>').join(''):'<p>Noch keine Deals gespeichert.</p>'}
window.removeWatch=i=>{let w=getWatch();w.splice(i,1);setWatch(w)};window.loadWatch=i=>{const d=getWatch()[i];if(!d)return;['product','buy','sell','cost','sold','active','comps','certainty','risk','target','days'].forEach(k=>{if(d[k]!=null&&$(k))$(k).value=d[k]});calc();location.hash='#check'};
function renderForecasts(){const fs=getForecasts();$('forecastList').innerHTML=fs.length?'<h3 style="margin-top:18px">Vorgemerkte Erwartungen</h3>'+fs.map((f,i)=>'<div class="forecastCard"><strong>'+esc(f.product||'Unbenannter Deal')+'</strong><br><small>Erwartet: Verkauf '+eur(f.sell)+' · Gewinn '+eur(f.profit)+' · '+Number(f.days||0)+' Tage · Score '+(f.score??'–')+'/100</small><div class="actions"><button class="secondary" onclick="chooseForecast('+i+')">Als verkauft erfassen</button><button class="secondary" onclick="removeForecast('+i+')">Entfernen</button></div></div>').join(''):'<p>Du hast noch keine Erwartung vorgemerkt.</p>'}
window.removeForecast=i=>{let fs=getForecasts();fs.splice(i,1);setForecasts(fs)};window.chooseForecast=i=>{const f=getForecasts()[i];if(!f)return;$('selectedForecast').value=f.id;$('actualSell').value=f.sell;$('actualCost').value=f.cost;$('actualDays').value=f.days;$('outcomeHint').textContent='Ausgewählt: '+(f.product||'Deal')+' · Erwartung vom '+new Date(f.savedAt).toLocaleDateString('de-DE');location.hash='#realitaet'};
function renderOutcomes(){const os=getOutcomes();$('outcomeList').innerHTML=os.length?'<h3 style="margin-top:18px">Deine Ergebnis-Historie</h3>'+os.map(o=>{const dp=o.actualProfit-o.expectedProfit,dd=o.actualDays-o.expectedDays,cls=dp>=0?'deltaPos':'deltaNeg';return '<div class="historyCard"><div class="historyTop"><div><strong>'+esc(o.product||'Deal')+'</strong><br><small>Erwartung: '+eur(o.expectedProfit)+' Gewinn · '+o.expectedDays+' Tage<br>Tatsächlich: '+eur(o.actualProfit)+' Gewinn · '+o.actualDays+' Tage</small></div><div><strong class="'+cls+'">Gewinn Δ '+(dp>=0?'+':'')+eur(dp)+'</strong><br><small>Tage Δ '+(dd>=0?'+':'')+dd+'</small></div></div></div>'}).join(''):'<p>Noch keine tatsächlichen Ergebnisse gespeichert.</p>'}
function dl(name,text,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
const safeText=v=>{const s=String(v??'');return /^[=+\-@\t\r]/.test(s)?"'"+s:s};
const csv=v=>'"'+safeText(v).replaceAll('"','""')+'"';
document.querySelectorAll('input').forEach(x=>x.addEventListener('input',()=>{if(!['actualSell','actualCost','actualDays'].includes(x.id))calc()}));
$('saveRules').onclick=()=>{localStorage.setItem(RULES,JSON.stringify({minProfit:num('ruleProfit'),minRoi:num('ruleRoi'),maxRisk:cl(num('ruleRisk'),1,5),minQuality:cl(num('ruleQuality'),0,100)}));calc()};
$('save').onclick=()=>{let w=getWatch();w.unshift({...c});setWatch(w)};
$('copy').onclick=async()=>{let t='DEALFAZ '+(c.product||'Deal')+': '+c.score+'/100 · '+c.verdict+' · Gewinn '+eur(c.profit)+' · ROI '+c.roi.toFixed(1)+'%';try{await navigator.clipboard.writeText(t)}catch{}};
$('share').onclick=async()=>{let p=new URLSearchParams({product:c.product,buy:c.buy,sell:c.sell,cost:c.cost,sold:c.sold,active:c.active,comps:c.comps,certainty:c.certainty,risk:c.risk,target:c.target,days:c.days}),url=location.origin+location.pathname+'?'+p.toString(),text='DEALFAZ '+(c.product||'Deal')+': '+c.score+'/100 · '+c.verdict;if(navigator.share)try{await navigator.share({title:'DEALFAZ DealCheck',text,url})}catch{}else try{await navigator.clipboard.writeText(url)}catch{}};
$('exportJson').onclick=()=>dl('dealfaz-watchlist.json',JSON.stringify(getWatch(),null,2),'application/json');
$('exportCsv').onclick=()=>{let w=getWatch(),rows=[['Produkt','Einkauf','Verkauf','Kosten','Score','Signal','ROI','Datenqualität'],...w.map(d=>[d.product,d.buy,d.sell,d.cost,d.score,d.verdict,Number(d.roi||0).toFixed(1),d.quality])];dl('dealfaz-watchlist.csv','\ufeff'+rows.map(r=>r.map(csv).join(';')).join('\n'),'text/csv;charset=utf-8')};
$('importJson').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(Array.isArray(x))setWatch(x)}catch{alert('Backup konnte nicht gelesen werden.')}};$('clearWatch').onclick=()=>{if(confirm('Lokale Watchlist wirklich leeren?'))setWatch([])};
$('saveForecast').onclick=()=>{const fs=getForecasts(),f={...c,id:'f_'+Date.now(),savedAt:Date.now()};fs.unshift(f);setForecasts(fs);$('outcomeHint').textContent='Erwartung lokal vorgemerkt: '+(f.product||'Deal')};
$('saveOutcome').onclick=()=>{const id=$('selectedForecast').value,fs=getForecasts(),f=fs.find(x=>x.id===id);if(!f){$('outcomeHint').textContent='Bitte zuerst eine vorgemerkte Erwartung auswählen.';return}const actualSell=num('actualSell'),actualCost=num('actualCost'),actualDays=num('actualDays');if(actualDays<1){$('outcomeHint').textContent='Bitte tatsächliche Verkaufstage eintragen.';return}const actualProfit=actualSell-f.buy-actualCost,actualRoi=f.buy?actualProfit/f.buy*100:0,o={id:'o_'+Date.now(),forecastId:f.id,product:f.product,buy:f.buy,expectedSell:f.sell,expectedCost:f.cost,expectedProfit:f.profit,expectedRoi:f.roi,expectedDays:f.days,actualSell,actualCost,actualProfit,actualRoi,actualDays,savedAt:Date.now()};const os=getOutcomes();os.unshift(o);setOutcomes(os);$('outcomeHint').textContent='Tatsächliches Ergebnis wurde nur lokal gespeichert.'};
$('exportOutcomes').onclick=()=>{const os=getOutcomes(),rows=[['Produkt','Erwarteter Verkauf','Tatsächlicher Verkauf','Erwarteter Gewinn','Tatsächlicher Gewinn','Erwartete Tage','Tatsächliche Tage'],...os.map(o=>[o.product,o.expectedSell,o.actualSell,o.expectedProfit,o.actualProfit,o.expectedDays,o.actualDays])];dl('dealfaz-ergebnisse.csv','\ufeff'+rows.map(r=>r.map(csv).join(';')).join('\n'),'text/csv;charset=utf-8')};
document.querySelectorAll('[data-legal]').forEach(b=>b.onclick=()=>document.querySelectorAll('.legalPage').forEach(x=>x.classList.toggle('open',x.id===b.dataset.legal)));
const qs=new URLSearchParams(location.search);['product','buy','sell','cost','sold','active','comps','certainty','risk','target','days'].forEach(k=>{if(qs.has(k)&&$(k))$(k).value=qs.get(k)});const r=getRules();$('ruleProfit').value=r.minProfit;$('ruleRoi').value=r.minRoi;$('ruleRisk').value=r.maxRisk;$('ruleQuality').value=r.minQuality;renderWatch();renderForecasts();renderOutcomes();calc();